warning_threshold: 1000

excluded:
  - Pods
  - Templates
  - "*/.build"
  - SolanaSwift
  - BEPureLayout
  - LazySubject
  - BECollectionView
  - THPinViewController
  - FeeRelayerSwift
  - OrcaSwapSwift
  - RenVMSwift
  - TransakSwift
  - "p2p_wallet/Scenes/Main/SwapToken/SerumSwap(Unstable)"

disabled_rules:
  - identifier_name
  - cyclomatic_complexity
  - large_tuple
  - trailing_whitespace
  - force_try
  - force_cast
  - function_body_length
  - multiple_closures_with_trailing_closure
  - redundant_string_enum_value
  - inert_defer
  - nesting
  - type_name
  - opening_brace
  - shorthand_operator
  - todo
  - trailing_comma
  - line_length

function_parameter_count:
  warning: 15
  error: 20

file_length:
  warning: 500
  error: 700

type_body_length:
  warning: 400

custom_rules:
  swiftgen_assets:
    name: "SwiftGen Assets"
    regex: '(UIImage|UIColor)(\.init)?\(named: ?"?.+"?(, ?in:.+?, ?compatibleWith:.+?)?\)|#imageLiteral\(resourceName: ?".+"\)'
    message: "Use Asset.<asset> instead"
    severity: error
  swiftgen_colors:
    name: "SwiftGen Colors"
    regex: '(UIColor(\.init)?|#colorLiteral)\(((red|displayP3Red):.+?,green:.+?,blue:.+?,alpha:.+?)|(white:.+?,alpha:.+?)|(hue:.+?,saturation:.+?,brightness:.+?,alpha:.+?)\)'
    message: "Use ColorName.<color> instead"
    severity: error
  swiftgen_fonts:
    name: "SwiftGen Fonts"
    regex: 'UIFont(\.init)?\(name: ?"?.+"?, ?size:.+?\)'
    message: "Use FontFamily.<family>.<variant>.size(<size>) instead"
    severity: error
  swiftgen_strings:
    name: "SwiftGen Strings"
    regex: 'NSLocalizedString'
    message: "Use L10n.key instead"
    severity: error
  next_arrow:
    name: "Next arrow"
    regex: '(image: \.nextArrow)|(UIImageView(\.init)?\(width: 14, height: 21, image: (UIImage)?\.chevronRight\))'
    message: "Use UIView.defaultNextArrow() instead"
    severity: warning
  paragraph_style:
    name: "Pragraph style"
    regex: 'NSParagraphStyle\(\)'
    message: "Don't construct NSParagraphStyle directly, use withParagraphStyle() method on NSMutableAttributedString instead"
    severity: warning
  close_banner_button:
    name: "Close banner button"
    regex: 'image: (UIImage)?\.closeBannerButton'
    message: "Use UIView.closeBannerButton instead"
    severity: warning
  clipboard_direct_api:
    name: "UIPasteboard"
    regex: 'UIPasteboard.general'
    message: "Use ClipboardManager instead"
    severity: warning
  timer_memory_leak:
    name: "Timer with target causes memory leak, use block instead"
    regex: 'Timer.scheduledTimer\(.+selector'
    message: "Use block instead"
    serverity: error
