name: p2p_wallet

# how to add localization back:
# 1. remove scripts in preGenCommand+postGenCommand
# 2. repace in project.yml:

#- path: p2p_wallet
#          name: p2p_wallet
#          excludes:
#            - "Resources/*.lproj-backup/*"

# to
#- p2p_wallet

# 3. Remove these comment when done

options:
    deploymentTarget: 
        iOS: 14.0
    groupSortPosition: top
    minimumXcodeGenVersion: 2.18.0
    preGenCommand: sh Scripts/preGenCommand.sh
    postGenCommand: sh Scripts/postGenCommand.sh

configs:
    Debug: debug
    Test: release
    Release: release

configFiles:
    Debug: p2p_wallet/Config.xcconfig
    Test: p2p_wallet/Config.xcconfig
    Release: p2p_wallet/Config.xcconfig

settings:
    base:
        MARKETING_VERSION: 2.3
    configs:
        Debug:
            VALIDATE_PRODUCT: false
            SWIFT_COMPILATION_MODE: singlefile
            SWIFT_OPTIMIZATION_LEVEL: "-Onone"
            ENABLE_TESTABILITY: true
            ENABLE_BITCODE: false
            DEBUG_INFORMATION_FORMAT: dwarf
            ONLY_ACTIVE_ARCH: true
            SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
            GCC_PREPROCESSOR_DEFINITIONS:
            - DEBUG=1
        Test:
            VALIDATE_PRODUCT: true
            SWIFT_COMPILATION_MODE: wholemodule
            SWIFT_OPTIMIZATION_LEVEL: "-O"
            ENABLE_TESTABILITY: false
            ENABLE_BITCODE: false
            DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
            ONLY_ACTIVE_ARCH: false
            SWIFT_ACTIVE_COMPILATION_CONDITIONS: TEST
            GCC_PREPROCESSOR_DEFINITIONS:
            - TEST=1
        Release:
            VALIDATE_PRODUCT: true
            SWIFT_COMPILATION_MODE: wholemodule
            SWIFT_OPTIMIZATION_LEVEL: "-O"
            ENABLE_TESTABILITY: true
            ENABLE_BITCODE: false
            DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
            ONLY_ACTIVE_ARCH: false
            SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
            GCC_PREPROCESSOR_DEFINITIONS:
            - RELEASE=1

aggregateTargets:
    Detect unused code:
        buildScripts:
        - name: SwiftGen
          script: ${PWD}/Pods/SwiftGen/bin/swiftgen config run --config ${PWD}/swiftgen.yml
        - name: Periphery
          script: ${PWD}/Pods/Periphery/periphery scan --workspace p2p_wallet.xcworkspace --format xcode

targets:
    p2p_wallet:
        type: application
        platform: iOS
        deploymentTarget: 14.0
        sources:
        - path: p2p_wallet
          name: p2p_wallet
          excludes:
            - "Resources/*.lproj-backup/*"
            - "**/*.a"
            - "**/GoogleService-Info.plist"
        - path: README.MD
        preBuildScripts:
          - script: |
                  # Name of the resource we're selectively copying
                  GOOGLESERVICE_INFO_PLIST=GoogleService-Info.plist

                  # Get references to dev and prod versions of the GoogleService-Info.plist
                  # NOTE: These should only live on the file system and should NOT be part of the target (since we'll be adding them to the target manually)
                  GOOGLESERVICE_INFO_DEV=${PROJECT_DIR}/${TARGET_NAME}/Firebase/Dev/${GOOGLESERVICE_INFO_PLIST}
                  GOOGLESERVICE_INFO_PROD=${PROJECT_DIR}/${TARGET_NAME}/Firebase/Prod/${GOOGLESERVICE_INFO_PLIST}

                  # Make sure the dev version of GoogleService-Info.plist exists
                  echo "Looking for ${GOOGLESERVICE_INFO_PLIST} in ${GOOGLESERVICE_INFO_DEV}"
                  if [ ! -f $GOOGLESERVICE_INFO_DEV ]
                  then
                      echo "No Development GoogleService-Info.plist found. Please ensure it's in the proper directory."
                      exit 1
                  fi

                  # Make sure the prod version of GoogleService-Info.plist exists
                  echo "Looking for ${GOOGLESERVICE_INFO_PLIST} in ${GOOGLESERVICE_INFO_PROD}"
                  if [ ! -f $GOOGLESERVICE_INFO_PROD ]
                  then
                      echo "No Production GoogleService-Info.plist found. Please ensure it's in the proper directory."
                      exit 1
                  fi

                  # Get a reference to the destination location for the GoogleService-Info.plist
                  PLIST_DESTINATION=${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app
                  echo "Will copy ${GOOGLESERVICE_INFO_PLIST} to final destination: ${PLIST_DESTINATION}"

                  # Copy over the prod GoogleService-Info.plist for Release builds
                  if [ "${CONFIGURATION}" == "Release" ]
                  then
                      echo "Using ${GOOGLESERVICE_INFO_PROD}"
                      cp "${GOOGLESERVICE_INFO_PROD}" "${PLIST_DESTINATION}"
                  else
                      echo "Using ${GOOGLESERVICE_INFO_DEV}"
                      cp "${GOOGLESERVICE_INFO_DEV}" "${PLIST_DESTINATION}"
                  fi
            name: "[SCRIPT] Setup Firebase Environment GoogleService-Info.plist"

          - script: |
                  if [ "${CONFIGURATION}" = "Release" ]; then
                    echo "Swiftgen is disabled in Release mode"
                    exit 0
                  fi
                  "$PODS_ROOT/SwiftGen/bin/swiftgen"
            name: "[SCRIPT] Swiftgen Run"
        postBuildScripts:
          - script: |
                  if [ "${CONFIGURATION}" != "Debug" ]; then
                      ${PODS_ROOT}/FirebaseCrashlytics/run
                  fi
            name: "[SCRIPT] Crashlytics Run"
            inputFiles:
              - "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}"
              - "$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"
        settings:
            base:
                TARGETED_DEVICE_FAMILY: 1
                PRODUCT_BUNDLE_IDENTIFIER: org.p2p.cyber
                DEVELOPMENT_TEAM: A72KN37UN2
                ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
                CODE_SIGN_IDENTITY: 'Apple Development'
                CODE_SIGN_ENTITLEMENTS: p2p_wallet/p2p_wallet.entitlements
                CODE_SIGN_STYLE: Automatic
                CURRENT_PROJECT_VERSION: 1
                OTHER_LDFLAGS:
                - "$(inherited)"
                - "-framework"
                - "\"BEPureLayout\""
                - "-framework"
                - "\"CFNetwork\""
                - "-framework"
                - "\"Foundation\""
                - "-framework"
                - "\"PureLayout\""
                - "-framework"
                - "\"RxCocoa\""
                - "-framework"
                - "\"RxRelay\""
                - "-framework"
                - "\"RxSwift\""
                - "-framework"
                - "\"SolanaSwift\""
                PRODUCT_NAME: "$(TARGET_NAME)"
                DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
            configs:
                Debug:
                    PRODUCT_BUNDLE_IDENTIFIER: org.p2p.cyber.test
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIconTest
                Test:
                    PRODUCT_BUNDLE_IDENTIFIER: org.p2p.cyber.test
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: TEST
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIconTest
                Release:
                    PRODUCT_BUNDLE_IDENTIFIER: org.p2p.cyber
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

        dependencies:
            - framework: Frameworks/keyapp.xcframework
              embed: false
