name: p2p_wallet

# how to add localization back:
# 1. remove scripts in preGenCommand+postGenCommand
# 2. repace in project.yml:

#- path: p2p_wallet
#          name: p2p_wallet
#          excludes:
#            - "Resources/*.lproj-backup/*"

# to
#- p2p_wallet

# 3. Remove these comment when done

options:
    deploymentTarget: 
        iOS: 14.0
    groupSortPosition: top
    minimumXcodeGenVersion: 2.18.0
    preGenCommand: sh Scripts/preGenCommand.sh
    postGenCommand: sh Scripts/postGenCommand.sh

configs:
    Debug: debug
    Test: release
    Release: release

configFiles:
    Debug: p2p_wallet/Config.xcconfig
    Test: p2p_wallet/Config.xcconfig
    Release: p2p_wallet/Config.xcconfig

settings:
    base:
        MARKETING_VERSION: 1.9.0
    configs:
        Debug:
            VALIDATE_PRODUCT: false
            SWIFT_COMPILATION_MODE: singlefile
            SWIFT_OPTIMIZATION_LEVEL: "-Onone"
            ENABLE_TESTABILITY: true
            ENABLE_BITCODE: false
            DEBUG_INFORMATION_FORMAT: dwarf
            ONLY_ACTIVE_ARCH: true
            SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
            GCC_PREPROCESSOR_DEFINITIONS:
            - DEBUG=1
        Test:
            VALIDATE_PRODUCT: true
            SWIFT_COMPILATION_MODE: wholemodule
            SWIFT_OPTIMIZATION_LEVEL: "-O"
            ENABLE_TESTABILITY: false
            ENABLE_BITCODE: false
            DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
            ONLY_ACTIVE_ARCH: false
            SWIFT_ACTIVE_COMPILATION_CONDITIONS: TEST
            GCC_PREPROCESSOR_DEFINITIONS:
            - TEST=1
        Release:
            VALIDATE_PRODUCT: true
            SWIFT_COMPILATION_MODE: wholemodule
            SWIFT_OPTIMIZATION_LEVEL: "-O"
            ENABLE_TESTABILITY: true
            ENABLE_BITCODE: true
            DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
            ONLY_ACTIVE_ARCH: false
            SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
            GCC_PREPROCESSOR_DEFINITIONS:
            - RELEASE=1

targets:
    p2p_wallet:
        type: application
        platform: iOS
        deploymentTarget: 14.0
        sources:
        - path: p2p_wallet
          name: p2p_wallet
          excludes:
            - "Resources/*.lproj-backup/*"
        - path: README.MD
        preBuildScripts:
          - script: |
                  if [ "${CONFIGURATION}" = "Release" ]; then
                    echo "Swiftgen is disabled in Release mode"
                    exit 0
                  fi
                  "$PODS_ROOT/SwiftGen/bin/swiftgen"
            name: "[SCRIPT] Swiftgen Run"
          - script: |
                  "$SRCROOT"/Scripts/formatAndLint.sh
            name: "[SCRIPT] Format and lint"
        postBuildScripts:
          - script: |
                  if [ "${CONFIGURATION}" != "Debug" ]; then
                      ${PODS_ROOT}/FirebaseCrashlytics/run -gsp ${SRCROOT}/p2p_wallet/GoogleService-Info.plist
                  fi
            name: "[SCRIPT] Crashlytics Run"
            inputFiles:
              - "${SRCROOT}/${BUILD_PRODUCTS_DIR}/${INFOPLIST_PATH}"
        settings:
            base:
                TARGETED_DEVICE_FAMILY: 1
                PRODUCT_BUNDLE_IDENTIFIER: org.p2p.cyber
                DEVELOPMENT_TEAM: A72KN37UN2
                ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
                CODE_SIGN_IDENTITY: 'Apple Development'
                CODE_SIGN_ENTITLEMENTS: p2p_wallet/p2p_wallet.entitlements
                CODE_SIGN_STYLE: Automatic
                CURRENT_PROJECT_VERSION: 1
                OTHER_LDFLAGS:
                - "$(inherited)"
                - "-framework"
                - "\"BEPureLayout\""
                - "-framework"
                - "\"CFNetwork\""
                - "-framework"
                - "\"Foundation\""
                - "-framework"
                - "\"PureLayout\""
                - "-framework"
                - "\"RxCocoa\""
                - "-framework"
                - "\"RxRelay\""
                - "-framework"
                - "\"RxSwift\""
                - "-framework"
                - "\"SolanaSwift\""
                PRODUCT_NAME: "$(TARGET_NAME)"
                DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
            configs:
                Debug:
                    PRODUCT_BUNDLE_IDENTIFIER: org.p2p.cyber.test
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIconTest
                Test:
                    PRODUCT_BUNDLE_IDENTIFIER: org.p2p.cyber.test
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: TEST
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIconTest
                Release:
                    PRODUCT_BUNDLE_IDENTIFIER: org.p2p.cyber
                    SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

    Detect Unused Code:
        type: app-extension.intents-service
        platform: iOS
        preBuildScripts:
          - script: |
                  "${PWD}/Pods/SwiftGen/bin/swiftgen config run --config ${PWD}/swiftgen.yml"
            name: "Swiftgen Run Script"
          - script: |
                  "${PWD}/Pods/Periphery/periphery scan --workspace p2p_wallet.xcworkspace"
            name: "Periphery Run Script"
        settings:
            base:
                PRODUCT_NAME: "$(TARGET_NAME)"
                TARGETED_DEVICE_FAMILY: 1
                CODE_SIGN_STYLE: Automatic
