public enum StrigaUserIndustry: String, CaseIterable, Codable {
    case accounting = "ACCOUNTING"
    case selfEmployed = "SELF_EMPLOYED"
    case audit = "AUDIT"
    case finance = "FINANCE"
    case publicSectorAdministration = "PUBLIC_SECTOR_ADMINISTRATION"
    case artEntertainment = "ART_ENTERTAINMENT"
    case autoAviation = "AUTO_AVIATION"
    case bankingLending = "BANKING_LENGING"
    case businessConsultancyLegal = "BUSINESS_CONSULTANCY_LEGAL"
    case constructionRepair = "CONSTRUCTION_REPAIR"
    case educationProfessionalServices = "EDUCATION_PROFESSIONAL_SERVICES"
    case informationalTechnologies = "INFORMATIONAL_TECHNOLOGIES"
    case tobaccoAlcohol = "TOBACCO_ALCOHOL"
    case gamingGambling = "GAMING_GAMBLING"
    case medicalServices = "MEDICAL_SERVICES"
    case manufacturing = "MANUFACTURING"
    case prMarketing = "PR_MARKETING"
    case preciousGoodsJewelry = "PRECIOUS_GOODS_JEWELRY"
    case nonGovernmentalOrganization = "NON_GOVERNMENTAL_ORGANIZATION"
    case insuranceSecurity = "INSURANCE_SECURITY"
    case retailWholesale = "RETAIL_WHOLESALE"
    case travelTourism = "TRAVEL_TOURISM"
    case freelancer = "FREELANCER"
    case student = "STUDENT"
    case retired = "RETIRED"
    case unemployed = "UNEMPOYED"
}
