# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match
    gym(scheme: 'p2p_wallet', export_method: 'ad-hoc', export_xcargs: '-allowProvisioningUpdates')
    # upload to firebase
    firebase_app_distribution(
      app: "1:553127941597:ios:a6c953f38501ab112c5234",
      groups: "dev_team",
      firebase_cli_token: "1//0e7sQVYQPvT2vCgYIARAAGA4SNwF-L9Irle7o4pw3SQrwWwwUdjFi_z8Jl3NI3fj3h9EOn6zjPX-_nBHtRKn9gNoHoY9HaUR7Wnw"
    )    
    # upload to browserstack
    upload_to_browserstack_app_live(
      browserstack_username: "veronikadedukhin1",
      browserstack_access_key: "KsDobGNSbeBdS7P8KpES",
    )
  end
end
