name: Run unit test

on: pull_request

jobs:
  unit-test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test --filter "FeeRelayerSwiftUnitTests" --enable-code-coverage
      # - name: Processing converage data
      #   run: |
      #     xcrun llvm-cov export -format="lcov" .build/debug/FeeRelayerSwiftUnitTests.xctest/Contents/MacOS/FeeRelayerSwiftUnitTests -instr-profile .build/debug/codecov/default.profdata > info.lcov

      # - uses: codecov/codecov-action@v3
      #   with:
      #     # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #     files: ./info.lcov # optional
      #     flags: unittests # optional
      #     name: codecov-umbrella # optional
      #     fail_ci_if_error: true # optional (default = false)
      #     verbose: true # optional (default = false)
