name: Auto deploy
on:
  pull_request:

concurrency:
  group: auto-deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  upload_build_for_testing:
    name: Upload build for testing
    if: ${{ contains(github.event.pull_request.labels.*.name, 'auto:qa-deploy') && !contains(github.event.pull_request.labels.*.name, 'high')  && !contains(github.event.pull_request.labels.*.name, 'no-qa') }}

    runs-on: macos-12

    steps:
      - name: Check out current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive
          token: ${{ secrets.SUBMODULES_ACCESS_TOKEN }}

      - name: Grant access to KeyAppUI
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.KEY_APP_UI_GIT_SSH }}

      - name: Copy xcconfig file
        run: |
          curl -o ./p2p_wallet/Config.xcconfig ${{ secrets.XCCONFIG_URL }}
        shell: bash

      - uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install project
        run: |
          chmod u+x Scripts/install.sh && Scripts/install.sh
        shell: bash

      - name: Upload to test
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: feature_test
        env:
          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
          DEVELOPER_APP_ID_TEST: '${{ secrets.DEVELOPER_APP_ID_TEST }}'
          PROVISIONING_PROFILE_SPECIFIER_ADHOC: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER_ADHOC }}'
          PROVISIONING_PROFILE_SPECIFIER_APPSTORE: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER_APPSTORE }}'
          APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
          PROVISIONING_REPO: '${{ secrets.PROVISIONING_REPO }}'
          FIREBASE_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'
          FIREBASE_APP_ID_TEST: '${{ secrets.FIREBASE_APP_ID_TEST }}'
          FIREBASE_CLI_TOKEN: '${{ secrets.FIREBASE_CLI_TOKEN }}'
          BROWSERSTACK_USERNAME: '${{ secrets.BROWSERSTACK_USERNAME }}'
          BROWSERSTACK_ACCESS_KEY: '${{ secrets.BROWSERSTACK_ACCESS_KEY }}'
          FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
          APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          IS_CI: '${{ secrets.IS_CI }}'
          SLACK_API_TOKEN: '${{ secrets.SLACK_API_TOKEN }}'
          JIRA_BASE_URL: '${{ secrets.JIRA_BASE_URL }}'
          XCCONFIG_URL: '${{ secrets.XCCONFIG_URL }}'
          SENTRY_TOKEN: '${{ secrets.SENTRY_TOKEN }}'
