name: Manually build feature test
on: 
  workflow_dispatch:
    inputs:
      with_high_priority:
        type: boolean
        description: With high priority
      move_to_rft:
        type: boolean
        description: Move task to Ready for testing
        default: true 
concurrency:
  group: manually-feature-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
    with:
      with_high_priority: ${{ inputs.with_high_priority }}
      move_to_rft: ${{ inputs.move_to_rft }}
      lane: "feature_test"
    secrets: inherit
